import Banner from '@/components/Banner'
import Header from '@/components/Header'
import { NextPage } from 'next'
import { Barlow_Condensed, Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })
const barlow = Barlow_Condensed({
  subsets: ['latin'],
  weight: '400'
})

const Home: NextPage = () => {
  return (
    <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#fff] lg:h-[140vh]'>
      <Head>
        <title>Home - Marflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      <main>
        {/* Banner */}
        <Banner />
        <section>
          {/* Row */}
          {/* Row */}
          {/* Row */}
        </section>


        <h2 className={`${inter.className} bg-red-100`}>helo tailwind</h2>
      </main>
    </div>
  )
}
export default Home